# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sagaTrip',
                'doc_host': 'https://tripathysagar.github.io',
                'git_url': 'https://github.com/tripathysagar/sagaTrip',
                'lib_path': 'sagaTrip'},
  'syms': {}}
