# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_complex.ipynb.

# %% auto 0
__all__ = ['Comp']

# %% ../nbs/00_complex.ipynb 3
class Comp:
    def __init__(self, real, img):
        self.real, self.img = real, img
    def __str__(self):
        sym = '-' if self.img < 0 else '+'
        return f"{self.real} {sym}{abs(self.img)}i"
    __repr__ = __str__
